from .add_spot import AddSpotCommand
from .allow import AllowCommand
from .anagram import AnagramCommand
from .avatar import AvatarCommand
# from .broadcast import BroadcastCommand
from .brute_force import BruteForceCommand
from .cancel import CancelCommand
from .chat_id import ChatIdCommand
from .chats import ChatsCommand
from .clear_rating import ClearRatingCommand
from .code_formats import CodeFormatsCommand
from .config import ConfigCommand
from .cordinates import CoordinatesCommand
from .delete_spot import DeleteSpotCommand
from .drop import DropCommand
from .forbid import ForbidCommand
from .game import GameCommand
from .game_config import GameConfigCommand
from .go import GoCommand
from .help import HelpCommand
from .hint import HintCommand
from .intersection import IntersectionCommand
from .letters_to_numbers import LettersToNumbersCommand
from .link import LinkCommand
from .mask import MaskCommand
from .maxwell import MaxwellCommand
from .morse import MorseCommand
from .notes import NotesCommand
from .numbers_to_letters import NumbersToLettersCommand
from .permission import PermissionCommand
from .pin_level import PinLevelCommand
from .question import QuestionCommand
from .rating import RatingCommand
from .restrict import RestrictCommand
from .romka import RomkaCommand
from .start import StartCommand
from .subscribe import SubscribeCommand
from .test import TestCommand
from .top import TopCommand
from .unpin_level import UnpinLevelCommand
from .user_id import UserIdCommand
from .write import WriteCommand
